name: Gatsby Application Build and Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Gatsby Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.3.0"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Install Gatsby
        run: npm install -g gatsby-cli

      - name: Build Gatsby Application
        run: gatsby build

      - name: Verify the Build Successful
        run: ls -la public